name = "LatticeBoltzmannModel"
uuid = "ab0093b4-0b25-4baf-a3dd-3bdf3b7dfdbc"
authors = ["GiggleLiu"]
version = "1.0.0-DEV"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[weakdeps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"

[extensions]
LatticeBoltzmannCUDAExt = "CUDA"

[compat]
CUDA = "5"
LinearAlgebra = "1"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
