name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    name: ${{ matrix.package }} - Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1' # latest stable
        os:
          - ubuntu-latest
        arch:
          - x64
        package:
          - MyFirstPackage
          - PhysicsSimulation
          - LatticeGasCA
          - ImageProcessing
          - KernelPCA
          - CompressedSensing
          - HappyMolecules
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: actions/cache@v1
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - name: "develop lib packages"
        run: make init-${{ matrix.package }}
      - uses: julia-actions/julia-buildpkg@v1
      - name: "run tests"
        run: make test-${{ matrix.package }}